export { default as Dashboard } from './Dashboard'
export { default as GameList } from './Game'
export { default as AddNewGame } from './AddGame'
export { default as GameDetails } from './Game/Details'
export { default as SmallGame} from './SmallGamePlay'